### ISSUE TITLE
about Wake-up words 

### ISSUE THREAD

**Issue by sunjunlishi** [cmusphinx/pocketsphinx#101]
Dear athor:
（.lm .dic）The number of small words is used to increase the number of wake-up words, and the result is very good. But on the ordinary computer, the speed is a bit slow. So increasing the matching speed of the specified word, the customer feels better. Can it be done on the code, and I'm going to study this part of the matching code

**Comment by sunjunlishi** [comment]
Direct output corresponds to the recognition probability of a wake-up word to determine whether or not it is activated; the speed is not faster.

**Comment by nshmyrev** [comment]
Sorry, it is hard to understand your question, you might want to put more effort in framing it properly.

**Comment by sunjunlishi** [comment]
For example, Hi GOOGLE, frame of each paragraph, we need to select the largest fraction of all phonemes HMM (frame). If we directly select HI of HMM (frame), G of HMM (L), and .......,we can see if the score satisfies the condition. Is this speed not faster?

**Comment by nshmyrev** [comment]
No, it does not work this way. The problem is that speech is continuous and pronunciation of H depends on I and on G a lot, you can not analyze them alone, you need to analyze them together. That is what keyword spotting mode is doing and it is running pretty fast, much faster than realtime even on Android. Only neural networks are faster.

**Comment by sunjunlishi** [comment]
![2](https://user-images.githubusercontent.com/11845664/33812553-42940eb8-de59-11e7-8c1c-238fe27dcb04.png)

![1](https://user-images.githubusercontent.com/11845664/33812548-3d79cc4c-de59-11e7-874c-a3850ab54fd9.png)

**Comment by sunjunlishi** [comment]
Is there a way to raise the speed, and must strictly follow the method of seeking the maximum probability of HMM

**Comment by nshmyrev** [comment]
Overall performance optimization require some algorithm understanding. Most of the time in keyword spotting is spent in acoustic computation, not in hmm, so you need to optimize acoustic computation instead of hmm. And you can start with profiling instead of random guess. People use neural networks for fast and efficient keyword spotting these days.

**Comment by sunjunlishi** [comment]
thank you
