### ISSUE TITLE
Error in generating 'Make' file

### ISSUE THREAD

**Issue by kaushal1214** [cmusphinx/pocketsphinx#134]
acmod.c: In function ‘acmod_read_scores’:
acmod.c:1037:56: error: macro "E_DEBUG" passed 3 arguments, but takes just 2
             acmod->senscr_frame, acmod->n_senone_active);

**Comment by chussong** [comment]
I imagine you've solved this by now, but in case anyone else comes across this: this is likely due to using the release version of sphinxbase instead of the most current code from GitHub. If you download, compile, and install [the GitHub version](https://github.com/cmusphinx/sphinxbase) it should be resolved.

It happens because the debug macros were redefined and the current code here references the newer versions.

**Comment by badc0ded** [comment]
I'm actually getting this with the github version that I just downloaded.

**Comment by nshmyrev** [comment]
@badc0ded you need to build both sphinxbase and pocketsphinx from github. Also you need to make sure you removed older installed versions.

**Comment by badc0ded** [comment]
Thank you, I actually figured that out right after commenting and then
tried to delete my comment before anybody wasted time on a response. Sorry
about that.

**Comment by Limag** [comment]
I propose to modify the README.md, because it is outdated at this point: "_You **must** have SphinxBase, which you can download from http://cmusphinx.sourceforge.net ._ "

**Comment by Coeur** [comment]
@Limag you can pull request that. :)

**Comment by dhdaines** [comment]
No longer relevant as SphinxBase is no longer relevant as of #250
