### ISSUE TITLE
Questions regarding language support

### ISSUE THREAD

**Issue by DonaldTsang** [cmusphinx/pocketsphinx#212]
According to https://github.com/pettarin/forced-alignment-tools some of the top multi-lingual Forced Aligners are Aeneas (which has slowed in development), CMUSphinx (this repo), and SPPAS.

I would like to ask, why does Sphinx not support more languages like Aeneas?
(reasoning: Support for Cantonese, Hakka, Min, Japanese, Korean Thai, Vietnamese, Tagalog, Malay etc.)

**Comment by nshmyrev** [comment]
Aeneas is using slightly different technology which enables quick support for many languages but the accuracy is not perfect, aeneas can only align very high quality books.

At the current state of things with cmusphinx technology the single language support takes us about 2-3 months to build a good model and quite some resources. Still, we have models for many languages (about 20 major languages we have built commercially, including Japanese, Korean and Tagalog for example) .

Maybe the technology will develop soon and we won't have to spend so much time on a new language, but for now it is pretty complex and slow.

**Comment by DonaldTsang** [comment]
@nshmyrev thanks for the response, but are those models and datasets open for the public to use for FOSS research and development? I am an advocate for Open Access. If it is possible, list all the publicly available language models such that people can know what to expect.

Also are there difficulties for parsing tonal languages for Cantonese, Hakka and Min due to design constraints?

**Comment by nshmyrev** [comment]
> thanks for the response, but are those models and datasets open for the public to use for FOSS research and development?

Public models from our recent developments are listed here (Mandarin Chinese, Spanish, Portuguese, Russian, German, French):

https://github.com/alphacep/vosk-api/blob/master/doc/models.md

as for databases, database are kind of useless thing to share anyway because things are changing very quickly and it is not very easy to use them anyway. It is more a living object than a static old-style data. Beside our project there are many other projects where you can find the data and models, the development is pretty scattered these days.

> Also are there difficulties for parsing tonal languages for Cantonese, Hakka and Min due to design constraints?

Not really, it is mainly about resources spend to support them. I prefer to work on major languages though first. We might work on Vietnamese for example.

**Comment by DonaldTsang** [comment]
> I prefer to work on major languages though first. We might work on Vietnamese for example.

That is pretty unfortunate to see Vietnamese (~75 million speakers) not being put on the same priority as Cantonese (~70 million speakers) when both are legal languages (Vietnam and Hong Kong respectively).

Also there are listings like https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers#Top_languages_by_population which details the number of speakers... and I would say that Hindi, Bengali, Japanese, Western Punjabi, Marathi, Telugu, Wu Chinese, Turkish, Korean, Tamil, Urdu, Javanese, Italian, Egyptian Arabic, Gujarati and Iranian Persian are all part of the top 25 languages (also including Cantonese and Vietnamese) BUT Dutch is 52nd and Greek is 74th... I would assume that we have Dutch and Greek devs that made the model.

**Comment by nshmyrev** [comment]
@DonaldTsang well, we can consider Cantonese, thats a great idea. In any case the major reason to support some language is interest of some party or company. If you can spread the word it would be great.

In Asia there is a SUSI assistant for example which we would like to support, but there are no resources on our side and no interest from outside unfortunately. If we would be supported by that assistant we might get bigger push on Asian languages.

**Comment by nshmyrev** [comment]
@DonaldTsang Btw, Vietnamese model has been just added https://github.com/alphacep/vosk-api/blob/master/doc/models.md, next probably will be Turkish and Hinglish. As for other languages, let me know.

**Comment by dhdaines** [comment]
Hello, for word-level force alignment you can always try the somewhat hacky but surprisingly effective universal approach as we are doing in the ReadAlongs project: https://github.com/ReadAlongs/Studio

I will close this as it isn't really a bug in PocketSphinx, though I would like to thank @nshmyrev  for all the work on training models in other languages!  We will be pulling these models into GitHub if possible since SourceForge is obsolete and considered harmful.
