### ISSUE TITLE
how to use this project?

### ISSUE THREAD

**Issue by elfc2000** [cmusphinx/pocketsphinx#276]
I had find some doc about this ,use  pocketsphinx_continuous  to recognize real-time speech。
But in this new version , I did't find pocketsphinx_continuous.exe  and I don't know how to recognize real-time voice. Please give me some samples for that. Thanks

**Comment by dhdaines** [comment]
Hi, the audio interface and pocketsphinx_continuous were removed because they did not work well and were hard to maintain.  Are you sure you really want to use pocketsphinx from the Windows command line for live speech recognition?  It may be fun to play with but I can't see this as a serious use case.

pocketsphinx_continuous.exe will not come back, but before the release there will be an example of how to do live recognition, the recommended way to do this is from Python using pyaudio and webrtcvad.

**Comment by dhdaines** [comment]
For a Python example see: https://github.com/cmusphinx/pocketsphinx/blob/master/cython/vad_example.py

**Comment by dhdaines** [comment]
For the simplest possible C and Python examples see https://github.com/cmusphinx/pocketsphinx/tree/master/examples
=
