### ISSUE TITLE
pocketsphinx binary hangs when called with no arguments

### ISSUE THREAD

**Issue by lenzo-ka** [cmusphinx/pocketsphinx#301]
If `pocketsphinx` is called with no arguments, it just sits there and doesn't use any cpu, and doesn't respond to control-C.

This is on macOS 12.6, YMMV

**Comment by lenzo-ka** [comment]
It also won't give any help if given -h or -help or --help, same behavior

**Comment by dhdaines** [comment]
Hi!  This is because it is reading from standard input, and the system call in question doesn't get interrupted by SIGINT.

This behaviour is logical and yet totally unexpected, so I will change it so that you have to pass an input file of `-` for it to read from stdin.  And likewise to get help more easily!
