### ISSUE TITLE
What is AlignmentEntry?

### ISSUE THREAD

**Issue by zyh3826** [cmusphinx/pocketsphinx#340]
Hi, thanks for your work, it's really nice.
I use the code below to run an alignment:
```python
with wave.open(args.audio, "rb") as audio:
    data = audio.getfp().read()
    decoder = Decoder(samprate=audio.getframerate())
    decoder.set_align_text(args.text)
    decoder.start_utt()
    decoder.process_raw(data, full_utt=True)
    decoder.end_utt()
    decoder.set_alignment()
    decoder.start_utt()
    decoder.process_raw(data, full_utt=True)
    decoder.end_utt()
    for word in decoder.get_alignment():
        print(list(word))
```
the result is an `AlignmentEntry` object, how can I find documents of this object? What are its attributions?  Can't find it in your documents.
![image](https://user-images.githubusercontent.com/31238754/236429607-8c943972-5ec7-4a7f-9331-bb0a0315f41f.png)

thanks a lot.

**Comment by zyh3826** [comment]
I also try this, get the same results:
```python
for word in decoder.get_alignment():
        for phone in word:
            for state in phone:
                print(word, phone, state)
```
![image](https://user-images.githubusercontent.com/31238754/236430428-91a44cb4-89b1-4c77-958c-cc3409a21168.png)

**Comment by dhdaines** [comment]
Hi! Sorry for the long time to reply, I am just catching up on PocketSphinx-related stuff now.

As it turns out the `AlignmentEntry` should be documented, but was accidentally left out of the online documentation - I will fix this in the next release, shortly.  You can see its documentation by running `python -m pydoc pocketsphinx._pocketsphinx.AlignmentEntry`

See also its docstring here: https://github.com/cmusphinx/pocketsphinx/blob/master/cython/_pocketsphinx.pyx#L1992

**Comment by zyh3826** [comment]
Got it, thanks for your reply
