### ISSUE TITLE
Unable to find Accoustic, Dictionnary and Model different from english. 

### ISSUE THREAD

**Issue by NicolasLasch** [cmusphinx/pocketsphinx#378]
Hey, I was wondering if there were a place where I could find other trained languages like French, Spanish or whatever.  For now on I found a French model, but without the right acoustic and dictionary it works not very well.  Thank you !

**Comment by dhdaines** [comment]
Hi!  There are some pre-trained models which still live on SourceForge for the moment:

https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/

Hoping to find the time to move them to github soon, they are of quite variable quality and performance.  (and generally not very good accuracy, because CMUSphinx isn't a very accurate speech recognizer :) )
