### ISSUE TITLE
Please create a label or a branch so it is easy to lock down to a specific version

### ISSUE THREAD

**Issue by jainanshul** [cmusphinx/pocketsphinx#45]
I am using pocketsphinx in my project and it is working well. However I would like to lock down the version of pocketsphinx to a specific branch or a tag so I don't keep on importing new commits as they come. It would be great if you guys can create a tag or a branch that could be used.

**Comment by luzfcb** [comment]
@nshmyrev First, thank you for this project. It would be incredible that with each new version (Even the pre-alpha versions), a git tag was created to mark which commit originated the referred version. I say the same for sphinxbase

**Comment by mbait** [comment]
In git branch or tag is just a textual alias to the commit hash, so use
hash instead.

On Apr 23, 2017 4:06 PM, "Fábio C. Barrionuevo da Luz" <
notifications@github.com> wrote:

@nshmyrev <https://github.com/nshmyrev> First, thank you for this project.
It would be incredible that with each new version (Even the pre-alpha
versions), a git tag was created to mark which commit originated the
referred version. I say the same for sphinxbase

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cmusphinx/pocketsphinx/issues/45#issuecomment-296495547>,
or mute the thread
