### ISSUE TITLE
Several issues concerning the acoustic model adaptation

### ISSUE THREAD

**Issue by nirvandy** [cmusphinx/pocketsphinx#62]
Hi sir,
Now,i am using the Mandarin acoustic model which you used to provide to do the Mandarin speech recognition.The effect is not bad.But i encountered two important problems:
1.Female's speech recognition effect is far less than the male's.
2.English letters' speech recognition effect is not good.

then according to the official tutorial's recommendation, i adapted the acoustic model .But the effect is not very good.So i have the following questions:

1.Are the sentences used to adapt the longer the better?
2.Is the numbers of sentences  the more the better? how many numbers is recommended?
3.Is acoustic model adaptation really effective? For example,can we change the situation which female' speech recognition effect is not good by adapting the default acoustic model? Or is it better to retrain a new acoustic model?

**Comment by nshmyrev** [comment]
It is better to collect data and retrain the model. You can use http://www.openslr.org/18/ as a start. You can add your data to the training.

Data requirements are listed in tutorial, for serious models you need > 100 hours of data.

You can also use tone-dependent phoneset in order to get better approximation.
